# SonarCloud configuration

# Must be unique in a given SonarCloud organization
sonar.projectKey=JoshnaChary_MindoulaDashBoard
sonar.organization=joshnachary

# Path to the source code
sonar.sources=src

# Excluded paths for logic (Tests should NOT be scanned as source code)
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/coverage/**,.next/**,.nuxt/**,out/**,android/**,ios/**,src/tests/**,**/__tests__/**

# Coverage Exclusions (Only exclude non-code/mock files)
sonar.coverage.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/coverage/**,android/**,ios/**,src/data/mock/**,src/core/navigation/types.ts

# Coverage report mapped to Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
