# SonarCloud configuration

# Must be unique in a given SonarCloud organization
sonar.projectKey=JoshnaChary_MindoulaDashBoard
sonar.organization=joshnachary

# Path to the source code
sonar.sources=.

# Excluded paths for logic
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/coverage/**,.next/**,.nuxt/**,out/**

# Coverage Exclusions
sonar.coverage.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/coverage/**

# Coverage report mapped to Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
